workflows:
  ios_build:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Create Flutter iOS folder
        script: |
          flutter create .
      - name: Get packages
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      testflight:
        enable: true
